### ISSUE TITLE
Errors on Mac due to carriage returns

### ISSUE THREAD

**Issue by ljharb** [bterlson/eshost-cli#12]
When I `npm install -g eshost` and then `eshost host` I get `env: node\r: No such file or directory` - it seems the file is full of Windows newline characters.

My guess is that this is breaking it on non-Windows systems - when I remove the `^M` chars, it seems to execute fine.

**Comment by bterlson** [comment]
Indeed, will be fixed in next release! Thanks :)

**Comment by bterlson** [comment]
Should be fixed now. Hopefully nuked all \r's from the repo. Linux users report success. LMK if you find otherwise.

**Comment by ljharb** [comment]
Seems fixed, thanks!
