### ISSUE TITLE
chalk.blue() produces nearly unreadable text in my terminal

### ISSUE THREAD

**Issue by ajklein** [bterlson/eshost-cli#15]
Would be nice if colors were configurable (right now I just pipe through cat)...

**Comment by bterlson** [comment]
Aww sad... maybe I need a --pretty/--no-pretty option like many other tools.

**Comment by michaelficarra** [comment]
@ajklein you should probably change your terminal's blue colour then. At some point, another tool is going to try to create blue text and it will be unreadable again.

**Comment by sindresorhus** [comment]
@ajklein Chalk maintainer here. Can you share a screenshot of how it looks? I thought we had [worked around that](https://github.com/chalk/chalk/blob/0d2144904b9b5769076106aa67583273e160f801/index.js#L14-L17).

`--color` and `--no-color` flags comes bundled with Chalk, so they just needs to be documented.

Though I would echo @michaelficarra's recommendation. You can either fix your terminal or open an issue on every command-line tool you use that uses the blue color. On behalf of maintainers, I hope you go with the former.

**Comment by ajklein** [comment]
Fwiw I followed @michaelficarra's entirely reasonable suggestion and changed my terminal, so I'm ok with closing this.
