### ISSUE TITLE
Add documentation for setting up eshost-cli

### ISSUE THREAD

**Issue by dilijev** [bterlson/eshost-cli#21]
For example https://gist.github.com/dilijev/d8f2fd58551360409b2ba3f50af144fd

**Comment by mathiasbynens** [comment]
jsvu simplifies the setup process: https://github.com/GoogleChromeLabs/jsvu#integration-with-eshost-cli 

Open PR to improve this for Windows: https://github.com/GoogleChromeLabs/jsvu/pull/36

**Comment by dilijev** [comment]
Thanks @mathiasbynens. Note that there's a suggestion here https://github.com/bterlson/eshost-cli/issues/49 for automating jsvu setup in eshost-cli. Closing this issue.
