### ISSUE TITLE
Test hooks for setting config file

### ISSUE THREAD

**Issue by bterlson** [bterlson/eshost-cli#38]
Sitting here with an empty eshost config, I feel like modifying the users config file is prone to failure. Can we add the appropriate test hooks to set the config path in Config.js instead?

**Comment by dilijev** [comment]
Running tests killed your config file? Are the tests not using a custom config file? Yeah that would seem like a good idea.

**Comment by bterlson** [comment]
The tests attempt to stash your user config away and then overwrite the user config, taking care to restore it at the end. I think my issue was I aborted the test run so the restore step never came.

**Comment by rwaldron** [comment]
@bterlson Yep, that sounds about right. I can work on this today
