### ISSUE TITLE
Preparing 3.5.0

### ISSUE THREAD

**Issue by dilijev** [bterlson/eshost-cli#40]
Since we've merged a number of features and created tests and increased test coverage, I'd like to update eshost-cli. Here's a draft of the release message:

# v3.5.0

* Add tests and enable Travis (@rwaldron #32)
* `--list` learned to sort by name (@dilijev #34)
* Learned `--edit`: allows modifying `--args` or `--tags` of a host (@dilijev #36)
* Learned `--unanimous, -u`: exit(0) and print nothing if all hosts agree, otherwise exit(1). (@dilijev #35, @rwaldron #37)

Did I miss anything we should call out? Anything blocking?

/cc @bterlson @rwaldron

**Comment by rwaldron** [comment]
Do we want to add @bterlson's windows test fixing? Either way, this is good by me!

**Comment by bterlson** [comment]
@rwaldron is 3.5.0 blocked on #41 / #42 at all?

**Comment by rwaldron** [comment]
Those are all landed now, so we might as well include those in v3.5.0: 

```
* Add tests and enable Travis (@rwaldron #32)
* `--list` learned to sort by name (@dilijev #34)
* Learned `--edit`: allows modifying `--args` or `--tags` of a host (@dilijev #36)
* Learned `--unanimous, -u`: exit(0) and print nothing if all hosts agree, otherwise exit(1). (@dilijev #35, @rwaldron #37)
* Add appveyor support (@rwaldron #44)
* Use --config ... and Config.defaultConfigPath for test-safe configuration. (@rwaldron #43)
```

**Comment by dilijev** [comment]
#42 landed? Looks like it's still open?

**Comment by bterlson** [comment]
#42 seems to be future testing work. We can release without it.

**Comment by dilijev** [comment]
Done! https://github.com/bterlson/eshost-cli/releases/tag/v3.5.0
