### ISSUE TITLE
jsvu-d8 reporting "Unexpected end of input" for basic test scripts 

### ISSUE THREAD

**Issue by dilijev** [bterlson/eshost-cli#50]
Verified that the latest eshost is installed (3.8.0 at time of writing) and the jsvu binary is up-to-date (latest):

```
> eshost -ie "42"
## Source
print(42)

#### jsvu-d8
SyntaxError: Unexpected end of input
```

The same script runs just fine directly under the jsvu d8 binary.

```
>where d8
C:\Users\doilij\.jsvu\d8.cmd
>d8 -e "print(42)"
42
```

Is there some d8 support change that is needed in eshost-cli or eshost or both?

**Comment by dilijev** [comment]
Looks like this has been resolved in a newer build.

**Comment by mathiasbynens** [comment]
I am often seeing the same issue when using eshost, but not when using `d8` directly. The latest example:

```
$ eshost -x 'a = []; a[2**32-2] = 1; a.unshift(1);'
#### V8 --harmony
SyntaxError: Unexpected end of input

$ v8 -e 'a = []; a[2**32-2] = 1; a.unshift(1);'
unnamed:1: RangeError: Invalid array length
a = []; a[2**32-2] = 1; a.unshift(1);
                          ^
RangeError: Invalid array length
    at Array.unshift (<anonymous>)
    at unnamed:1:27
```

Can we reopen this issue?
