### ISSUE TITLE
Consistent order for host results

### ISSUE THREAD

**Issue by bakkot** [bterlson/eshost-cli#53]
It's a little weird to run the same command twice and get output in a different order.

This means delaying results from fast engines to wait for slower ones, but does not increase total runtime.

**Comment by bakkot** [comment]
(Meant to do this myself, but haven't gotten to it yet, so I'm submitting an issue to keep track.)

**Comment by dilijev** [comment]
`-s` sorts results that match output, but yeah

**Comment by dilijev** [comment]
With regards to -s, sorting the groups should probably be done by alpha order of first entry?
