### ISSUE TITLE
 Support for the module goal

### ISSUE THREAD

**Issue by mathiasbynens** [bterlson/eshost-cli#62]
It looks like `eshost` supports modules per https://github.com/bterlson/eshost/pull/61. It would be great to have this functionality available in `eshost-cli` as well!

**Comment by rwaldron** [comment]
I'll work on that this week

**Comment by mathiasbynens** [comment]
Is this uploaded somewhere?

**Comment by mathiasbynens** [comment]
What's the status of this? :)

**Comment by mathiasbynens** [comment]
This is now available!
