### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by ToNiQian** [bterlson/eshost-cli#75]
![image](https://user-images.githubusercontent.com/10736608/93745427-1df87380-fc26-11ea-93f7-847cd6214fd3.png)

**Comment by mathiasbynens** [comment]
This doesn't seem to be released yet?

**Comment by rwaldron** [comment]
Indeed! Sorry about that. I'll get it out today.

**Comment by mathiasbynens** [comment]
Thanks!

**Comment by rwaldron** [comment]
@mathiasbynens no problem, and sorry about the delay on that! https://github.com/bterlson/eshost-cli/releases/tag/v7.7.0
